### ISSUE TITLE
gpu

### ISSUE THREAD

**Issue by 5-Daisy** [BrianPulfer/PapersReimplementations#1]
Hello, dear author, this vit you wrote is easy to understand and very easy to use, but how do I use it on gpu, and where should I modify the code?

**Comment by BrianPulfer** [comment]
Dear @5-Daisy ,

You can use the model on GPU as it is usually done for PyTorch models ([link to doc](https://pytorch.org/docs/stable/notes/cuda.html)). This is standard PyTorch.

In the provided code, it is sufficient to select the device (in main, before creating the ViT):
`device = torch.device("cuda" if torch.cuda.is_available() else "cpu")`

Put the ViT to that device:
`model = MyViT((1, 28, 28), n_patches=7, hidden_d=20, n_heads=2, out_d=10)`
`model.to(device)`

And put the MNIST data to device as well (after lines 155 and 171):
`x, y = batch`
`x, y = x.to(device), y.to(device)`

Note that function `get_positional_embeddings` returns a tensor that is not on the device (hence, it automatically goes to CPU). You need to put positional embeddings to GPU as well.

I Hope this was helpful.

**Comment by 5-Daisy** [comment]
Then I think the problem should be in the function get_positional_embeddings, how should I modify it in this function?

**Comment by 5-Daisy** [comment]
![image](https://user-images.githubusercontent.com/87062479/174432650-a55a4136-2720-4da2-bb9a-4d7f8d8f9ca8.png)
I modified it like this, but it still doesn't work

**Comment by BrianPulfer** [comment]
I updated the script such that it can be run on GPU as well.

I simply added a parameter "device" to the model
<img width="754" alt="Screenshot 2022-06-18 at 12 23 50" src="https://user-images.githubusercontent.com/42559439/174433938-df43aa52-c2cc-4345-a7c8-cd0afe6dec5e.png">

which is used in the forward method to move the embeddings tensor to the GPU.
<img width="848" alt="Screenshot 2022-06-18 at 12 24 03" src="https://user-images.githubusercontent.com/42559439/174433943-4dd8c0b4-577c-4b45-ba2e-f2d5f6691b16.png">

In the main, we just need to specify a device and pass it to the model. The model is then also put to the device.
<img width="788" alt="Screenshot 2022-06-18 at 12 36 50" src="https://user-images.githubusercontent.com/42559439/174433998-75625f40-c7dd-43d2-b2b8-4c5e8382486f.png">

**Comment by 5-Daisy** [comment]
![image](https://user-images.githubusercontent.com/87062479/174434602-183479fc-d048-4904-a085-962caefa68d2.png)
emmmm, it doesn't seem right, I use my own data set, some operations on the data are correct, but still an error will be reported

**Comment by BrianPulfer** [comment]
Right, the `q_mappings`, `k_mappings` and `v_mappings` in `MyMSA` needed to be put inside a `nn.ModuleList`. I updated the code. Does it work now?

**Comment by 5-Daisy** [comment]
Ok, now it can run on gpu, thank you very much, I am only a sophomore student from China, but I am very interested in deep learning, can you add your contact information?
